blog/src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PostRepository::class)
 */
class Post
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="text")
     */
    private $intro;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="text")
     */
    private $content_html;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_live;

    /**
     * @ORM\Column(type="datetime")
     */
    private $live_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;


    /**
     * @ORM\ManyToOne(targetEntity=Media::class, inversedBy="posts")
     */
    private $thumbnail;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="posts")
     */
    private $category;

    /**
     * @ORM\ManyToMany(targetEntity=Tag::class, inversedBy="posts")
     */
    private $tags;

    /**
     * @ORM\OneToMany(targetEntity=Revision::class, mappedBy="post_id", orphanRemoval=true)
     */
    private $revisions;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
        $this->revisions = new ArrayCollection();
        $this->newsletterReaders = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getIntro(): ?string
    {
        return $this->intro;
    }

    public function setIntro(string $intro): self
    {
        $this->intro = $intro;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getIsLive(): ?bool
    {
        return $this->is_live;
    }

    public function setIsLive(bool $is_live): self
    {
        $this->is_live = $is_live;

        return $this;
    }

    public function getLiveAt(): ?\DateTimeInterface
    {
        return $this->live_at;
    }

    public function setLiveAt(\DateTimeInterface $live_at): self
    {
        $this->live_at = $live_at;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getThumbnail(): ?Media
    {
        return $this->thumbnail;
    }

    public function setThumbnail(?Media $thumbnail): self
    {
        $this->thumbnail = $thumbnail;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->tags->contains($tag)) {
            $this->tags->removeElement($tag);
        }

        return $this;
    }

    /**
     * @return Collection|Revision[]
     */
    public function getRevisions(): Collection
    {
        return $this->revisions;
    }

    public function addRevision(Revision $revision): self
    {
        if (!$this->revisions->contains($revision)) {
            $this->revisions[] = $revision;
            $revision->setPostId($this);
        }

        return $this;
    }

    public function removeRevision(Revision $revision): self
    {
        if ($this->revisions->contains($revision)) {
            $this->revisions->removeElement($revision);
            // set the owning side to null (unless already changed)
            if ($revision->getPostId() === $this) {
                $revision->setPostId(null);
            }
        }

        return $this;
    }

    public function setContentHtml(?string $content_html): self
    {
        $this->content_html = $content_html;
        return $this;
    }

    public function getContentHtml(): ?string
    {
        return $this->content_html;
    }
}

blog/templates/home/404.html.twig
{% extends "base.html.twig" %}

{% block title %}Erreur 404{% endblock %}

{% block body %}
    <div class="container-404">
        <div class="section-404">
            <h1>404</h1>
            <p>La page demandée n'a pas été trouvée :(</p>
            <p><a href="/">Retourner à l'accueil</a></p>
        </div>
    </div>
{% endblock %}

{% block footer %}
{% endblock %}

blog/templates/home/archive.html.twig
{% extends "base.html.twig" %}

{% block title %}Archives{% endblock %}

{% block body %}
    <div class="archive-section">
        <div class="archive-title">
            <h1>Archives</h1>
        </div>
        <div class="archive-list">
            <div class="year-date">2020</div>
            <ul>
                {% for post in year2020 %}
                    <li><a href="{{ path('post.show', {slug: post.slug}) }}">
                        <h2>{{ post.title }}<span class="post-date"> - {{ post.liveAt|format_date(locale='fr') }}</span></h2>
                    </a></li>
                {% endfor %}
            </ul>

            <div class="year-date">2019</div>
            <ul>
                {% for post in year2019 %}
                    <li><a href="{{ path('post.show', {slug: post.slug}) }}">
                        <h2>{{ post.title }}<span class="post-date"> - {{ post.liveAt|format_date(locale='fr') }}</span></h2>
                    </a></li>
                {% endfor %}
            </ul>

            <div class="year-date">2018</div>
            <ul>
                {% for post in year2018 %}
                    <li><a href="{{ path('post.show', {slug: post.slug}) }}">
                        <h2>{{ post.title }}<span class="post-date"> - {{ post.liveAt|format_date(locale='fr') }}</span></h2>
                    </a></li>
                {% endfor %}
            </ul>

            <div class="year-date">2017</div>
            <ul>
                {% for post in year2017 %}
                    <li><a href="{{ path('post.show', {slug: post.slug}) }}">
                        <h2>{{ post.title }}<span class="post-date"> - {{ post.liveAt|format_date(locale='fr') }}</span></h2>
                    </a></li>
                {% endfor %}
            </ul>

            <div class="year-date">2016</div>
            <ul>
                {% for post in year2016 %}
                    <li><a href="{{ path('post.show', {slug: post.slug}) }}">
                        <h2>{{ post.title }}<span class="post-date"> - {{ post.liveAt|format_date(locale='fr') }}</span></h2>
                    </a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

blog/templates/home/category.html.twig
{% extends "base.html.twig" %}

{% block title %}Catégorie : {{ category.label }}{% endblock %}

{% block open_graph %}
    <meta property="og:title" content="{{ category.label }} - Kelou.fr" />
    <meta property="og:type" content="article" />
    <meta property="og:url" content="https://kelou.fr/category/{{ category.label }}" />
    <meta property="og:image" content="{{ app.request.getSchemeAndHttpHost() }}{{ asset('images/favicons/apple-touch-icon.png') }}" />
    <meta property="og:description" content="{{ category.description }}" />
{% endblock %}

{% block body %}
    <div class="tag-section">
        <h1>Catégorie : {{ category.label }}</h1>

        <div class="section-list">
            {% for post in posts %}
                <a href="{{ path('post.show', {slug: post.slug}) }}">
                    <div class="post small-shadow">
                        <div class="post-img">
                            <img class="lazyload" data-src="{% if post.thumbnail %}
                                    {{ vich_uploader_asset(post.thumbnail, 'mediaFile') | imagine_filter('post_thumbnail') }}
                                {% endif %}" alt="{{ post.title }}">
                        </div>
                        <div class="post-infos">
                            <h2 class="post-title">{{ post.title }}<span class="post-date">- {{ post.liveAt|format_date(locale='fr') }}</span></h2>
                            <p class="post-abstract">{{ post.intro }}</p>
                            <div class="post-read-more"><button class="btn btn-read-more">Lire la suite ...</button></div>
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}

blog/templates/home/contact.html.twig
{% extends "base.html.twig" %}

{% block title %}Contact{% endblock %}

{% block body %}
    <div class="contact-section">
        <div class="contact-title">
            <h1>ME CONTACTER</h1>
        </div>
        <div class="form-group">
            {% for label, messages in app.flashes %}
                {% for message in messages %}
                    <div class="flash-message flash-{{ label }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endfor %}
            {{ form_start(form) }}
                <div class="inputs-row">
                    <label style="display:block;height:0;width:0;color:#2d3743;" for="contact_form_name">Prénom</label>
                    {{ form_widget(form.name) }}
                    <label style="display:block;height:0;width:0;color:#2d3743;" for="contact_form_email">Email</label>
                    {{ form_widget(form.email) }}
                </div>
                <label style="display:block;height:0;width:0;color:#2d3743;" for="contact_form_message">Message</label>
                {{ form_widget(form.message) }}
                <button type="submit" class="btn">Envoyer</button>
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

blog/templates/home/homepage.html.twig
{% extends "base.html.twig" %}

{% block title %}Accueil{% endblock %}
{% block title_suffix %} - kelou.fr - Informatique, Programmation et  Devlpt personnel{% endblock %}

{% block body %}
    <div class="introduction">
        <h2>Blog</h2>
        <p class="content">"Kelou" signifie "journal" en breton. Sur ce blog, suivez les pérégrinations d'un jeune développeur dans son apprentissage à travers des écrits sur ses projets et les moments importants de cette aventure.<br /><br /><span class="color-primary">Retrouvez chaque semaine de nouvelles astuces, conseils et projets inspirants pour devenir un meilleur développeur.</span></p>
    </div>

    <div class="flashes" id="posts">
        {% for label, messages in app.flashes %}
            {% for message in messages %}
                <div class="flash-message flash-{{ label }}">
                    {{ message|raw }}
                </div>
            {% endfor %}
        {% endfor %}
    </div>

    <div class="main">
        <div class="sidebar">
            <div class="about-sidebar small-shadow">
                <div class="sidebar-title">À propos de moi</div>
                <div class="abstract">
                    <img class="lazyload" data-src="{{ asset('images/profile-pic.jpg') }}" alt="CASTEL Clément">
                    <div class="infos">
                        <h3>CASTEL Clément</h3>
                        <p>Fondateur, développeur et rédacteur de <b>kelou.fr</b></p>
                    </div>
                </div>
                <p class="about-text">Étudiant-ingénieur en développement logiciel spécialité sécurité. Fondateur du blog kelou.fr en 2016.<br />Passionné d'informatique, mathématiques, développement personnel et sport.</p>
            </div>
            <div class="newsletter-sidebar">
                <div class="sidebar-title">Newsletter</div>
                <p class="newsletter-text">Je ne publie pas tous les articles en public sur le blog. Je réserve les meilleurs aux abonnés de ma newsletter.<br /><br />Si vous souhaitez en faire partie, remplissez le formulaire ci-dessous.<br /><b>Je vous propose de vous envoyer la newsletter les quatres prochaines semaines. Ensuite, vous aurez le choix entre vous réinscrire pour devenir un membre permanent ou ne pas continuer.</b></p>
                <div class="form-group">
                    {{ form_start(newsletterForm) }}
                        <label style="height:0;width:0;color:#2d3743;" for="newsletter_register_form_name">Prénom</label>
                        {{ form_widget(newsletterForm.name) }}
                        <label style="height:0;width:0;color:#2d3743;" for="newsletter_register_form_email">Email</label>
                        {{ form_widget(newsletterForm.email) }}
                        <button type="submit" class="btn">Submit</button>
                    {{ form_end(newsletterForm) }}
                </div>
            </div>

            <div class="categories-sidebar small-shadow">
                <div class="sidebar-title">Catégories</div>
                <ul class="categories-list">
                    {% for category in categories %}
                        <li class="category-entry {% if category.label == 'MASTERCLASS'%}category-entry-primary{% endif %}"><a href="{{ path('category.index', {label: category.label}) }}">{{ category.label }}</a></li>
                    {% endfor %}
                </ul>
            </div>

        </div>
        <div class="latests">
            <div class="latests-title">Derniers articles {% if page != 1 %} (page {{ page }}) {% endif %}: </div>
            <div class="month-section">
                <div class="month-title"></div>

                {% for post in posts %}
                    <a href="{{ path('post.show', {slug: post.slug}) }}">
                        <div class="post small-shadow">
                            <div class="post-img">
                                <img class="lazyload" data-src="{% if post.thumbnail %}
                                    {{ vich_uploader_asset(post.thumbnail, 'mediaFile') | imagine_filter('post_thumbnail') }}
                                {% endif %}" alt="{{ post.title }}">
                            </div>
                            <div class="post-infos">
                                <h2 class="post-title">{{ post.title }}<span class="post-date"> - {{ post.liveAt|format_date(locale='fr') }}</span></h2>
                                <p class="post-abstract">{{ post.intro }}</p>
                                <div class="post-read-more"><button class="btn btn-read-more">Lire la suite ...</button></div>
                            </div>
                        </div>
                    </a>
                {% endfor %}

                {{ knp_pagination_render(posts) }}
            </div>
        </div>
    </div>

{% endblock %}







{# additional stylesheet
    {% block stylesheets %}
        {{ encore_entry_link_tags('admin') }}
    {% endblock %}
#}

{# additional script
    {% block javascripts %}
        {{ encore_entry_script_tags('admin') }}
    {% endblock %}
#}

blog/templates/home/newsletter.html.twig
{% extends "base.html.twig" %}

{% block title %}Newsletter{% endblock %}

{% block body %}
    <div class="flashes">
        {% for label, messages in app.flashes %}
            {% for message in messages %}
                <div class="flash-message flash-{{ label }}">
                    {{ message|raw }}
                </div>
            {% endfor %}
        {% endfor %}
    </div>

    {{ include('blocks/_newsletter.html.twig') }}
{% endblock %}

blog/templates/home/post.html.twig
{% extends "base.html.twig" %}


{% block stylesheets %}
    {{ encore_entry_link_tags('post') }}
{% endblock %}

{% block title %}{{ post.title }}{% endblock %}

{% block head %}
<meta name="description" content="{{ post.intro }}">
{% endblock %}

{% block open_graph %}
    <meta property="og:title" content="{{ post.title}} - Kelou.fr" />
    <meta property="og:type" content="article" />
    <meta property="og:url" content="https://kelou.fr/post/{{ post.slug }}" />
    <meta property="og:image" content="{{ app.request.getSchemeAndHttpHost() }}{{ vich_uploader_asset(post.thumbnail, 'mediaFile') }}" />
    <meta property="og:description" content="{{ post.intro }}" />
{% endblock %}

{% block body %}
    <div class="post-main">
        <div class="flashes">
            {% for label, messages in app.flashes %}
                {% for message in messages %}
                    <div class="flash-message flash-{{ label }}">
                        {{ message|raw }}
                    </div>
                {% endfor %}
            {% endfor %}
        </div>

        <div class="post-title"><h1 class="post-title">{{ post.title }}<span class="post-date"> - {{ post.liveAt|format_date(locale='fr') }}</span></h1></div>

        <div class="post-content">
            <div class="md-output">
                {{ post.contentHtml|raw }}
            </div>
        </div>

        <div class="post-tags">
            <a href="{{ path('category.index', {label: post.category.label }) }}"><div class="post-tag post-category">#{{ post.category }}</div></a>
            {% for tag in post.tags %}
                <a href="{{ path('tag.index', {label: tag.label}) }}"><div class="post-tag">#{{ tag.label }}</div></a>
            {% endfor %}
        </div>

        <div class="post-comment">
            <button><a href="/contact?post={{ post.title }}">Poster un commentaire ?</a></button>
        </div>
    </div>
    {{ include('blocks/_newsletter.html.twig') }}


    {% block javascripts %}
        {{ encore_entry_script_tags('post') }}
    {% endblock %}
{% endblock %}

blog/templates/home/robots-txt.html.twig
Sitemap: https://{{ domain }}/sitemap.xml

blog/templates/home/search.html.twig
{% extends "base.html.twig" %}

{% block title %}Recherche{% endblock %}

{% block body %}
    <div class="tag-section">
        <h1>🔍 Recherche{% if formTitle %} : {{ formTitle }}{% endif %}</h1>

        <div class="section-search">
            <div class="form-group">
                {{ form_start(form) }}
                <label style="height:0;width:0;color:#2d3743;margin-bottom:-2px;" for="search_title">Titre</label>
                {{ form_widget(form.title) }}
                <button type="submit" class="btn">Rechercher</button>
                {{ form_end(form) }}
            </div>
        </div>

        <div class="section-list">
            {% for post in posts %}
                <a href="{{ path('post.show', {slug: post.slug}) }}">
                    <div class="post small-shadow">
                        <div class="post-img">
                            <img class="lazyload" data-src="{% if post.thumbnail %}
                                    {{ vich_uploader_asset(post.thumbnail, 'mediaFile') | imagine_filter('post_thumbnail') }}
                                {% endif %}" alt="{{ post.title }}">
                        </div>
                        <div class="post-infos">
                            <h2 class="post-title">{{ post.title }}<span class="post-date">- {{ post.liveAt|format_date(locale='fr') }}</span></h2>
                            <p class="post-abstract">{{ post.intro }}</p>
                            <div class="post-read-more"><button class="btn btn-read-more">Lire la suite ...</button></div>
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}

blog/templates/home/sitemap-xml.html.twig
<?xml version='1.0' encoding='UTF-8'?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <url>
        <loc>https://kelou.fr/</loc>
        <lastmod>{{ "now"|date("Y-m-d") }}</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://kelou.fr/contact</loc>
        <lastmod>{{ "now"|date("Y-m-d") }}</lastmod>
    </url>
    <url>
        <loc>https://kelou.fr/archive</loc>
        <lastmod>{{ "now"|date("Y-m-d") }}</lastmod>
    </url>
    <url>
        <loc>https://kelou.fr/sitemap</loc>
        <lastmod>{{ "now"|date("Y-m-d") }}</lastmod>
    </url>
    <url>
        <loc>https://kelou.fr/newsletter</loc>
        <lastmod>{{ "now"|date("Y-m-d") }}</lastmod>
    </url>
    {% for post in posts %}
        <url>
            <loc>https://kelou.fr/post/{{ post.slug }}</loc>
            <lastmod>{{ post.updatedAt|date("Y-m-d") }}</lastmod>
        </url>
    {% endfor %}
    {% for category in categories %}
        <url>
            <loc>https://kelou.fr/category/{{ category.label }}</loc>
            <lastmod>{{ "now"|date("Y-m-d") }}</lastmod>
        </url>
    {% endfor %}
    {% for tag in tags %}
        <url>
            <loc>https://kelou.fr/tag/{{ tag.label }}</loc>
            <lastmod>{{ "now"|date("Y-m-d") }}</lastmod>
        </url>
    {% endfor %}
    {% for post in veille_posts %}
        <url>
            <loc>https://kelou.fr/veille/post/{{ post.slug }}</loc>
            <lastmod>{{ post.updatedAt|date("Y-m-d") }}</lastmod>
        </url>
    {% endfor %}
</urlset>

blog/templates/home/sitemap.html.twig
{% extends "base.html.twig" %}

{% block title %}Sitemap{% endblock %}

{% block body %}
    <div class="sitemap-section">
        <h2>PUBLICATIONS</h2>
        {% for post in posts %}
            <a href="{{ path('post.show', {slug: post.slug}) }}"><h3> {{ post.title }}</h3></a>
        {% endfor %}

        <h2>CATÉGORIES</h2>
        {% for category in categories %}
            <a href="{{ path('category.index', {label: category.label}) }}"><h3>{{ category.label }}</h3></a>
        {% endfor %}

        <h2>TAGS</h2>
        {% for tag in tags %}
            <a href="{{ path('tag.index', {label: tag.label}) }}"><h3>{{ tag.label }}</h3></a>
        {% endfor %}

        <h2>VEILLE</h2>
        {% for post in veille_posts %}
            <a href="{{ path('veille.show', {slug: post.slug}) }}"><h3>{{ post.title }}</h3></a>
        {% endfor %}
    </div>
{% endblock %}

blog/templates/home/tag.html.twig
{% extends "base.html.twig" %}

{% block title %}Tag : {{ tag.label }}{% endblock %}

{% block open_graph %}
    <meta property="og:title" content="{{ tag.label }} - Kelou.fr" />
    <meta property="og:type" content="article" />
    <meta property="og:url" content="https://kelou.fr/tag/{{ tag.label }}" />
    <meta property="og:image" content="{{ app.request.getSchemeAndHttpHost() }}{{ asset('images/favicons/apple-touch-icon.png') }}" />
    <meta property="og:description" content="{{ tag.description }}" />
{% endblock %}

{% block body %}
    <div class="tag-section">
        <h1>TAG : {{ tag.label }}</h1>

        <div class="section-list">
            {% for post in posts %}
                <a href="{{ path('post.show', {slug: post.slug}) }}">
                    <div class="post small-shadow">
                        <div class="post-img">
                            <img class="lazyload" data-src="{% if post.thumbnail %}
                                    {{ vich_uploader_asset(post.thumbnail, 'mediaFile') | imagine_filter('post_thumbnail') }}
                                {% endif %}" alt="{{ post.title }}">
                        </div>
                        <div class="post-infos">
                            <h2 class="post-title">{{ post.title }}<span class="post-date">- {{ post.liveAt|format_date(locale='fr') }}</span></h2>
                            <p class="post-abstract">{{ post.intro }}</p>
                            <div class="post-read-more"><button class="btn btn-read-more">Lire la suite ...</button></div>
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}

blog/templates/home/veille-index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Veille{% endblock %}

{% block body %}
    <div class="tag-section">
        <h1>VEILLE</h1>

        <div class="section-list">
            {% for post in veille_posts %}
                <a href="{{ path('veille.show', {slug: post.slug}) }}">
                    <div class="post small-shadow">
                        <div class="post-infos">
                            <h2 class="post-title">{{ post.title }}<span class="post-date">- {{ post.createdAt|format_date(locale='fr') }}</span></h2>
                        </div>
                    </div>
                </a>
            {%  endfor %}
        </div>
    </div>
{% endblock %}

blog/templates/home/veille-post.html.twig
{% extends "base.html.twig" %}


{% block stylesheets %}
    {{ encore_entry_link_tags('post') }}
{% endblock %}

{% block title %}{{ post.title }}{% endblock %}

{% block open_graph %}
    <meta property="og:title" content="{{ post.title}} - Kelou.fr" />
    <meta property="og:type" content="article" />
    <meta property="og:url" content="https://kelou.fr/post/{{ post.slug }}" />
{% endblock %}

{% block body %}
    <div class="post-main">

        <div class="post-title"><h1 class="post-title">{{ post.title }}<span class="post-date"> - {{ post.createdAt|format_date(locale='fr') }}</span></h1></div>

        <div class="post-content veille-post-content">
            <div class="md-output">
                {{ post.contentHtml|raw }}
            </div>
        </div>

        <div></div>
    </div>


    {% block javascripts %}
        {{ encore_entry_script_tags('post') }}
    {% endblock %}
{% endblock %}